### ISSUE TITLE
Add babel preprocessor

### ISSUE THREAD

**Issue by kaisermann** [kaisermann/svelte-preprocess#108]
**Is your feature request related to a problem? Please describe.**

Nope, just came to mind.

**Describe the solution you'd like**

Should we add a `babel` preprocessor?  Do people want/need to transpile their script tags at the preprocess step? Maybe to use some new syntax? Or should we leave this to the bundler?

It would probably work exactly as `postcss`, that is, you would pass `babel: true` or `babel: { ... options }` to the options object.

**Comment by kaisermann** [comment]
Was playing around with this and the only valid case I found was when using new syntax, such as optional operator and nullish coalescing, which the svelte compiler doesn't support.

**Comment by vandie** [comment]
I mean having babel would be nice for projects that need to support slightly older browsers. but I wouldn't say it's 100% needed.

**Comment by kaisermann** [comment]
@vandie As a preprocessor, babel shouldn't be allowed to transpile to older browsers, since it would result in a wrong svelte syntax, i.e commonJS vs esm and the compiler would still generate modern js. To support older browsers, babel has to be added to the bundle step so it's possible to transpile the compiled components instead.

That's my main question about this right now: is it really useful to have a babel preprocessor? I can only imagine use-cases of too-modern syntax and wanting to transform the script with some kind of babel plugin.

**Comment by vandie** [comment]
@kaisermann, if we're not going back to older versions of JS for better browser support then I can't see it getting much use.

**Comment by sudomaxime** [comment]
Damn, I would love to be able to use optional chaining, class decorators and whatnot.

**Comment by shirakaba** [comment]
> I mean having babel would be nice for projects that need to support slightly older browsers. but I wouldn't say it's 100% needed.
>
> @kaisermann, if we're not going back to older versions of JS for better browser support then I can't see it getting much use.

@vandie I am developing a Svelte web app for the most widely-used Smart TVs in the UK market. Although they are somewhat recent (2017-2018 era), TV web browsers lag behind desktop web browsers in their feature set. Furthermore, the HbbTV spec only specifies ES5, so nothing can be taken for granted.

Svelte is a brilliant solution for these under-powered devices, where heavy JS payloads can really slow things down. However these devices do commonly need polyfills in order to use more modern JS features.

I'm currently having success post-processing my JS with Babel to meet my feature needs on Smart TVs, but pre-processing is still necessary to support the nullish coalescing operator which the Svelte compiler doesn't support for some reason.

**Comment by kaisermann** [comment]
Got some time to focus on this one and made a draft PR with babel working in auto-preprocess mode: https://github.com/kaisermann/svelte-preprocess/pull/121. I'll finish up what's missing and try to release it tomorrow 😁.


And @vandie, I feel you. I've used svelte in a very underpowered POS machine, running a webkit version from 2011. What an experience that was 😆

**Comment by kaisermann** [comment]
Released in `v3.5.0` 🎉 Check the readme: https://github.com/kaisermann/svelte-preprocess#modern-javascript-syntax to see some limitations
