### ISSUE TITLE
Moving from node-sass to sass creates issues with :global()

### ISSUE THREAD

**Issue by matt3224** [kaisermann/svelte-preprocess#133]
**Describe the bug**
Upon switching from node-sass to sass all instances of :global() that use sass features become broken

**Logs**
```bash
Invalid parent selector ":global(.pika)"
    ╷
240 │    &__label {
    │    ^^^^^^^^^
    ╵
  stdin 240:4  root stylesheet
internal/modules/cjs/loader.js:979
  throw err;
  ^
```

**To Reproduce**
https://github.com/matt3224/svelte-preprocess-repro

**Expected behavior**
I expect whether using node-sass or sass both should compile the same, node-sass appears to have the right behaviour

**Information about your project:**

- Your operating system: macOS 10.15.4

- `svelte-preprocess` version: 3.7.1

- Whether your project uses Webpack or Rollup: Rollup

Thank you!

**Comment by kaisermann** [comment]
Hey @mat3224 :wave: It seems this is caused by some peculiarity in the way `dart-sass` handle simple selectors, which is probably different from what `node-sass` does. Unfortunately, this is way outside of the scope of this library 😞 . However, if you don't mind adding `:global` to all the other selectors inside your `style` tag, you can use the [`globalStyle` preprocessor](https://github.com/kaisermann/svelte-preprocess/#global-style) and be done with it 😁

**Comment by matt3224** [comment]
Hey, that is a shame thanks for taking a look!

Maybe pop something in the readme which flags this issue for others who may run into this

**Comment by zolotokrylin** [comment]
I bumped into this issue. `global` worked. Would be nice to add it to the docs as Matt mentioned 👍  would save me 40 mins of research time 😉 but anyway, that's for your lib. It's useful!
