### ISSUE TITLE
svelte v3 support?

### ISSUE THREAD

**Issue by tonyrewin** [kaisermann/svelte-preprocess#18]

**Comment by kaisermann** [comment]
Svelte v3 changes the `preprocess` step a little bit. Instead of having one processor for markup, one for style and one for script, it's now possible to pass a list of processors. This package will be adapted to support this new use case, but it'll probably be just a collection of ready-to-use processors which you can import and add to your `preprocess` queue. 

There's a somewhat old branch (https://github.com/kaisermann/svelte-preprocess/tree/v3) that (I hope so) shows how it's going to look like.

**Comment by kaisermann** [comment]
Oh, in theory, the current version should work with `v3` as well. I'm still not sure if changing to separated processors is the best way forward :thinking:

**Comment by tonyrewin** [comment]
https://github.com/kaisermann/svelte-preprocess/compare/v3 as i can see here it is easy to keep backward compatibility in this case

**Comment by kaisermann** [comment]
Just released `v2.6.0` which supports both ways. You can import standalone processors if desired, but you can also use the main method to get a generic single processor.
