### ISSUE TITLE
Question about reloading in external template

### ISSUE THREAD

**Issue by alvin** [kaisermann/svelte-preprocess#3]
Hello, avid PUG fan here!

I'm using the default sapper starter-template with `preprocess: require('svelte-preprocess')({})` added to the svelte-loader {options}.  pug pre-processing is working great, _however_ I have to restart the dev server after any change to the template.pug file. 

![image](https://user-images.githubusercontent.com/16319/42243886-9d25321c-7ec7-11e8-9c7d-8a814e61a150.png)

Adding the .pug extension to the existing {extensions} and {test} places in server.config.js and/or client.config.js files didn't seem to help.  Any ideas?

**Comment by alvin** [comment]
[https://github.com/foxflow/sapper-template](url) 
Here's a public fork with the pug edition of the starter template.

**Comment by kaisermann** [comment]
@alvin That's happening because `external files` are handled on the `preprocess` step only. Currently, there's no way to `watch` those for changes (at least I couldn't think of any). For now, what you can do is to `save` your `index.html` whenever you want the `dev server` to load your changes.

However, any suggestions are extremely welcome 😁
