### ISSUE TITLE
Postcss lint error in vs code

### ISSUE THREAD

**Issue by hgl** [kaisermann/svelte-preprocess#76]
Please take a look at this repo: [svelte.zip](https://github.com/kaisermann/svelte-preprocess/files/3749404/svelte.zip)

When using postcss with this media query ranges, vs code complains `) expected`:

```
@media (width >= 1px) {
}
```

even though `npm run dev` produces the right preprocessed code.

**Comment by duduindo** [comment]
@hgl , did you solve the problem?

**Comment by kaisermann** [comment]
Hey @hgl and @duduindo. It seems this issue is related the language server that `svelte-vscode` uses, please see https://github.com/UnwrittenFun/svelte-language-server/issues/37. Once that dependency and `svelte-vscode` itself are updated, this issue should be resolved (just tested it locally). If the problem persists after the update, feel free to reopen this issue 😁

**Comment by hgl** [comment]
I'll wait for the update. Thanks @kaisermann for taking the time to debug it.
