### ISSUE TITLE
Auto-subscriptions not working with typescript

### ISSUE THREAD

**Issue by ronhippler** [kaisermann/svelte-preprocess#81]
Auto-subscriptions don't work with typescript:

App.svelte
```html
<script lang="typescript">
  import { time } from "../store.ts";

  const formatter = new Intl.DateTimeFormat("en", {
    hour12: true,
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
  });
</script>

<h1>The time is {formatter.format($time)}</h1>
```

store.ts
```typescript
import { readable } from "svelte/store";

export const time = readable(new Date(), function start(set) {
  const interval = setInterval(() => {
    set(new Date());
  }, 1000);

  return function stop() {
    clearInterval(interval);
  };
});

```

gives me the error:
`Uncaught (in promise) ReferenceError: time is not defined`

Im using the Webpack loader.
Without `lang="typescript"` its working as espected.

**Comment by kaisermann** [comment]
Hi @ronhippler! Can you share your `tsconfig.json`?

**Comment by ronhippler** [comment]
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "*": ["types/*"] },
    "target": "es2017"
  },
  "include": ["./src/**"],
  "exclude": ["src/main/**/*.ts", "node_modules"]
}
```

**Comment by cortopy** [comment]
I can confirm this behaviour. It took me a while to work out what was happening, but even the basic example [from the tutorial]() is broken in typescript using svelte-preprocessor.

The reason is that if an import is not referenced in the `<script>`, then typescript compiler assumes that it's an unused import and removes it from transpiled code. **Even if the import is referenced as an auto subscription in the `html`**

So in the basic example, we would have to do something like:

```svelte
<script>
	import { count } from './stores.js';
	import Incrementer from './Incrementer.svelte';
	import Decrementer from './Decrementer.svelte';
	import Resetter from './Resetter.svelte';

        count; // this reference stops ts from removing the import
</script>

<h1>The count is {$count}</h1>

<Incrementer/>
<Decrementer/>
<Resetter/>
```

The reference can be anything: a mere expression like in the example (meaningless), a `console.log`, etc. In cases in which you use or manipulate the auto subscription `$count` in your `<script>` this is not required

**Comment by kaisermann** [comment]
Hopefully fixed on #90 🎉

**Comment by cortopy** [comment]
@kaisermann Thanks so much for the speedy fix!!! Using autosubscriptions in the HTML works great now. However, I've just bumped into another case which is not currently supported.

In the following:

```html
<script lang="ts">
	import { count } from './stores.js';
	import Incrementer from './Incrementer.svelte';
	import Decrementer from './Decrementer.svelte';
	import Resetter from './Resetter.svelte';

        let isLarge = $count > 10;
</script>

<h1>Count is now {isLarge ? "large" : "small"}</h1>

<Incrementer/>
<Decrementer/>
<Resetter/>
```

two errors are thrown because (1) `count` is not used and (2) `$count` is undefined.

I know this example is pretty dumb because the evaluation could be done in the HTML, but basically using autosubscriptions in the `<script>` confuses the ts transpiler.

I'm guessing this is a tough one

**Comment by kaisermann** [comment]
Great to know that fix is working for you! Now... For that new issue... Yeah, that's a hard one. @lukeed came with the same problem in discord earlier this week. Can you open a new issue specific for this one? I have no idea how to fix that for now, but will start thinking about it.
